modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/Cy4Shot/JED/issues"

[[mods]]
modId="jed"
version="${file.jarVersion}"
displayName="Just Enough Descriptions"
logoFile="jed.png" 

displayURL="https://github.com/Cy4Shot/JED/"

credits="Cy4 for the code, TruePenut for the logo, and many many people for the descriptions and translations!" 
authors="Cy4" 
description='''
This mod adds descriptions to every Item and Block in MC!
'''

[[dependencies.jed]] 
    modId="forge" 
    mandatory=true 
    versionRange="[39,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.jed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
